// frontend-vue/src/views/system/role/index.vue
<script setup lang="ts">
import SakuraCard from '@/components/sakura-card/index.vue'
import SakuraPagination from '@/components/sakura-pagination/index.vue'
import { useTable } from '@/hooks/useTable.ts'
import { ref, useTemplateRef } from 'vue'
import type { PageDto } from '@/types/type.ts'
import { ElMessage, ElMessageBox } from 'element-plus'
import roleApi from '@/api/system/role'
import type { RoleQuery, RoleVo } from '@/api/system/role/type.ts'
import RoleDialog from '@/views/system/role/components/role-dialog.vue'
import SetMenuDialog from '@/views/system/role/components/set-menu-dialog.vue'

const queryParams = ref<RoleQuery>({
  keyword: '',
})
const { pagination, list, search } = useTable((params: PageDto<RoleQuery>) => roleApi.getRoleData(params), {
  params: queryParams.value,
})

const setMenuDialogRef = useTemplateRef<InstanceType<typeof SetMenuDialog>>('setMenuDialog')
const setMenu = (id: string) => {
  setMenuDialogRef.value?.open(id)
}

const roleDialogRef = useTemplateRef<InstanceType<typeof RoleDialog>>('roleDialog')
const addRole = () => {
  roleDialogRef.value?.open()
}
const updateRole = (row: RoleVo) => {
  roleDialogRef.value?.open(row)
}
const deleteRole = (id: string) => {
  ElMessageBox.confirm('确定删除吗？', '提示').then(() => {
    roleApi.deleteRole(id).then(() => {
      ElMessage.success('删除成功')
      search()
    })
  })
}
</script>

<template>
  <sakura-card title="角色管理">
    <template #tools>
      <el-button type="primary" @click="addRole">新增角色</el-button>
      <div class="right">
        <div class="item">
          <div class="label">关键字</div>
          <el-input placeholder="请输入角色名称、编码" v-model="queryParams.keyword" clearable style="width: 240px" />
        </div>
        <div class="item">
          <el-button v-permission="'sys.role.query'" type="primary" @click="search">查询</el-button>
        </div>
      </div>
    </template>
    <el-table :data="list" style="width: 100%" max-height="100%">
      <el-table-column prop="roleName" width="200" label="角色名称" />
      <el-table-column prop="roleCode" width="200" label="角色编码" />
      <el-table-column prop="description" width="400" label="描述" />
      <el-table-column label="操作">
        <template #default="{ row }">
          <el-space>
            <a v-permission="'sys.role.set_menu'" @click="setMenu(row.id)">分配权限</a>
            <a v-permission="'sys.role.update'" @click="updateRole(row)">编辑</a>
            <a v-permission="'sys.role.delete'" @click="deleteRole(row.id)">删除</a>
          </el-space>
        </template>
      </el-table-column>
    </el-table>
    <sakura-pagination :pagination />
    <role-dialog ref="roleDialog" @update="search" />
    <set-menu-dialog ref="setMenuDialog" />
  </sakura-card>
</template>

<style scoped lang="scss">
.avatar {
  width: 60px;
  height: 60px;
  border-radius: 50%;
}
</style>

// frontend-react/src/views/system/role/index.tsx
import { Button, Form, Input, Modal, Space, Table, TableProps } from 'antd'
import useTable from '@/hooks/useTable.ts'
import { useRef } from 'react'
import { RoleVo } from '@/api/system/role/type.ts'
import roleApi from '@/api/system/role'
import RoleModal, { RoleModalRef } from '@/views/system/role/components/role-modal.tsx'
import AuthButton from '@/components/auth-button'
import SetMenuModal, { SetMenuModalRef } from '@/views/system/role/components/set-menu-modal.tsx'

function Role() {
  const [form] = Form.useForm()
  const { list, pagination, search, refresh } = useTable({
    api: roleApi.getRoleData,
    form,
  })

  const columns: TableProps<RoleVo>['columns'] = [
    {
      title: '角色名称',
      dataIndex: 'roleName',
    },
    {
      title: '角色编码',
      dataIndex: 'roleCode',
    },
    {
      title: '描述',
      dataIndex: 'description',
    },
    {
      title: '操作',
      dataIndex: 'action',
      render: (_, record) => (
        <Space size="middle">
          <AuthButton link auth={'sys.role.set_menu'} onClick={() => handleSetMenu(record.id)}>
            分配权限
          </AuthButton>
          <AuthButton link auth={'sys.role.update'} onClick={() => handleUpdate(record)}>
            编辑
          </AuthButton>
          <AuthButton link auth={'sys.role.delete'} onClick={() => handleDelete(record.id)}>
            删除
          </AuthButton>
        </Space>
      ),
    },
  ]

  const handleSetMenu = (id: string) => {
    setMenuModalRef.current?.open(id)
  }
  const handleUpdate = (row: RoleVo) => {
    roleModalRef.current?.open(row)
  }
  const handleAdd = () => {
    roleModalRef.current?.open()
  }
  const handleDelete = (id: string) => {
    Modal.confirm({
      title: '提示',
      content: '确定删除吗?',
      onOk: async () => {
        await roleApi.deleteRole(id)
        await refresh()
      },
    })
  }

  const roleModalRef = useRef<RoleModalRef>(null)
  const setMenuModalRef = useRef<SetMenuModalRef>(null)

  return (
    <div className="sakura-card">
      <div className="header">
        <div className="title">角色管理</div>
      </div>
      <div className="tools">
        <AuthButton type="primary" auth={'sys.role.add'} onClick={handleAdd}>
          新增
        </AuthButton>
        <Form layout="inline" form={form}>
          <Form.Item name="keyword" label="关键字">
            <Input placeholder="请输入角色名称、编码" allowClear />
          </Form.Item>
          <Form.Item>
            <AuthButton type="primary" auth={'sys.role.query'} onClick={search}>
              查询
            </AuthButton>
          </Form.Item>
        </Form>
      </div>
      <div className="content">
        <Table<RoleVo> columns={columns} dataSource={list} pagination={pagination} rowKey="id" />
      </div>
      <RoleModal ref={roleModalRef} update={refresh} />
      <SetMenuModal ref={setMenuModalRef} update={refresh} />
    </div>
  )
}

export default Role
