// frontend-vue/src/views/home/index.vue
<script setup lang="ts">
import useUserStore from '@/stores/modules/user'
import { getTime } from '@/utils/utils'

defineOptions({ name: 'Home' })

const userStore = useUserStore()
</script>

<template>
  <el-card>
    <div class="box">
      <img :src="userStore.avatar" alt="" class="avatar" />
      <div class="bottom">
        <h3 class="title">{{ getTime() }}好呀{{ userStore.name }}</h3>
        <p class="subtitle">Sakura的管理系统</p>
      </div>
    </div>
  </el-card>
</template>

<style scoped lang="scss">
.box {
  display: flex;
  align-items: center;

  .avatar {
    width: 100px;
    height: 100px;
    border-radius: 50%;
  }

  .bottom {
    margin-left: 20px;

    .title {
      font-size: 30px;
      font-weight: 900;
      margin-bottom: 30px;
    }

    .subtitle {
      font-style: italic;
      color: skyblue;
    }
  }
}

.bottoms {
  margin-top: 10px;
  display: flex;
  justify-content: center;
}
</style>

// frontend-react/src/views/home/index.tsx
import { Card } from 'antd'
import userStore from '@/stores/user.ts'
import { getTime } from '@/utils/utils.ts'
import style from './index.module.less'

function Home() {
  const { userinfo } = userStore()
  return (
    <Card>
      <div className={style.box}>
        <img src={userinfo.avatar || undefined} alt="" className="avatar" />
        <div className="bottom">
          <h3 className="title">
            {getTime()}好呀{userinfo.name}
          </h3>
          <p className="subtitle">Sakura的管理系统</p>
        </div>
      </div>
    </Card>
  )
}

export default Home
