// frontend-vue/src/views/system/menu/index.vue
<script setup lang="ts">
import SakuraCard from '@/components/sakura-card/index.vue'
import { ref, useTemplateRef } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import menuApi from '@/api/system/menu'
import type { MenuForm, MenuVo } from '@/api/system/menu/type.ts'
import MenuDialog from '@/views/system/menu/components/menu-dialog.vue'

const tableData = ref<MenuVo[]>([])
const getMenuData = async () => {
  const res = await menuApi.getMenuData()
  tableData.value = res.data
}
getMenuData()

// 新增菜单
const menuDialogRef = useTemplateRef<InstanceType<typeof MenuDialog>>('menuDialog')
const handleAdd = (parentId: string) => {
  menuDialogRef.value?.addOpen(parentId)
}

// 编辑菜单
const handleUpdate = (row: MenuForm) => {
  menuDialogRef.value?.editOpen(row)
}

// 删除菜单
const handleDelete = (id: string) => {
  ElMessageBox.confirm('确定删除？', '提示').then(async () => {
    await menuApi.deleteMenu(id)
    ElMessage.success('删除成功')
    getMenuData()
  })
}
</script>

<template>
  <sakura-card title="菜单管理">
    <template #tools>
      <el-button type="primary" @click="handleAdd('0')">添加菜单</el-button>
    </template>
    <el-table :data="tableData" style="width: 100%" row-key="id" max-height="100%">
      <el-table-column prop="title" label="菜单名称" />
      <el-table-column prop="component" label="路由名称" />
      <el-table-column prop="perms" label="权限标识" />
      <el-table-column prop="status" label="状态">
        <template #default="{ row }">
          <el-tag :type="row.status == 1 ? 'success' : 'info'">
            {{ row.status == 1 ? '正常' : '禁用' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="sortValue" label="排序" />
      <el-table-column label="操作">
        <template #default="{ row }">
          <el-space>
            <a v-permission="'sys.menu.add'" @click="handleAdd(row.id)" v-if="row.type !== 2">新增</a>
            <a v-permission="'sys.menu.update'" @click="handleUpdate(row)">编辑</a>
            <a v-permission="'sys.menu.delete'" @click="handleDelete(row.id)">删除</a>
          </el-space>
        </template>
      </el-table-column>
    </el-table>
    <menu-dialog ref="menuDialog" @update="getMenuData" />
  </sakura-card>
</template>

<style scoped lang="scss"></style>

// frontend-react/src/views/system/menu/index.tsx
import { Button, Modal, Space, Table, TableProps, Tag } from 'antd'
import { useEffect, useRef, useState } from 'react'
import RoleModal, { RoleModalRef } from '@/views/system/role/components/role-modal.tsx'
import { MenuVo } from '@/api/system/menu/type.ts'
import menuApi from '@/api/system/menu'
import { transformData } from '@/utils/utils.ts'
import MenuModal, { MenuModalRef } from '@/views/system/menu/components/menu-modal.tsx'
import AuthButton from '@/components/auth-button'

function Menu() {
  const [list, setList] = useState<MenuVo[]>([])
  const getMenuData = async () => {
    const res = await menuApi.getMenuData()
    setList(transformData(res.data))
  }
  useEffect(() => {
    getMenuData()
  }, [])

  const columns: TableProps<MenuVo>['columns'] = [
    {
      title: '菜单名称',
      dataIndex: 'title',
    },
    {
      title: '路由名称',
      dataIndex: 'component',
    },
    {
      title: '权限标识',
      dataIndex: 'perms',
    },
    {
      title: '状态',
      dataIndex: 'status',
      render: (value: 0 | 1) => {
        return <Tag color={value === 1 ? 'success' : 'error'}>{value === 1 ? '正常' : '禁用'}</Tag>
      },
    },
    {
      title: '排序',
      dataIndex: 'sortValue',
    },
    {
      title: '操作',
      dataIndex: 'action',
      render: (_, record) => (
        <Space size="middle">
          {!(record.type === 2) && (
            <AuthButton link auth={'sys.menu.add'} onClick={() => handleAdd(record.id)}>
              新增
            </AuthButton>
          )}
          <AuthButton link auth={'sys.menu.update'} onClick={() => handleUpdate(record)}>
            编辑
          </AuthButton>
          <AuthButton link auth={'sys.menu.delete'} onClick={() => handleDelete(record.id)}>
            删除
          </AuthButton>
        </Space>
      ),
    },
  ]

  const handleUpdate = (row: MenuVo) => {
    menuModalRef.current?.editOpen(row)
  }
  const handleAdd = (parentId: string) => {
    menuModalRef.current?.addOpen(parentId)
  }
  const handleDelete = (id: string) => {
    Modal.confirm({
      title: '提示',
      content: '确定删除吗?',
      onOk: async () => {
        await menuApi.deleteMenu(id)
        await getMenuData()
      },
    })
  }

  const menuModalRef = useRef<MenuModalRef>(null)

  return (
    <div className="sakura-card">
      <div className="header">
        <div className="title">菜单管理</div>
      </div>
      <div className="tools">
        <AuthButton type="primary" auth={'sys.menu.add'} onClick={() => handleAdd('0')}>
          新增
        </AuthButton>
      </div>
      <div className="content">
        <Table<MenuVo> columns={columns} dataSource={list} rowKey="id" />
      </div>
      <MenuModal ref={menuModalRef} update={getMenuData} />
    </div>
  )
}

export default Menu
